repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'PYTHONPATH=. pylint "$@"' --
        language: system
        types: [python]
        args:
          [
            "-rn",  # Only display messages
            "-sn",  # Don't display the score
            "--rcfile=.pylintrc",  # Link to your config file
            "--load-plugins=pylint.extensions.docparams",
          ]